version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - checkout
      - run:
          name: Setup information
          command: |
            echo ${CIRCLE_BRANCH}
            pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Decrypt environment files
          command: npm run decrypt
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - package.json
            - firebase.json
            - .firebaserc
  test:
    docker:
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/project
    steps:
      - run:
          name: Testing
          command: npm run test
  lint:
    docker:
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/project
    steps:
      - run:
          name: Linting
          command: npm run lint
  deploy:
    docker:
      - image: circleci/node:10.16.3-browsers
    working_directory: ~/project
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Building
          command: npm run build:production
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: npm run deploy:firebase -- --token=$FIREBASE_TOKEN

workflows:
  version: 2
  -deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
